server:
  port: 7001
spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
      - id: authserver
        uri: lb://authserver
        predicates:
        - Path=/auth/**
      - id: order
        uri: lb://order
        predicates:
        - Path=/order/**
        filters:
        - StripPrefix=1
      - id: storage
        uri: lb://storage
        predicates:
        - Path=/storage/**
        filters:
        - StripPrefix=1

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: gzdzssredispassword


eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka